# Node.js LTS 버전 사용
FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 코드 복사 및 빌드
COPY . .
RUN yarn build

# Nginx를 사용하여 정적 파일 제공
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

# Nginx 포트 설정
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
