name: Deploy to GCP Cloud Storage

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    name: Deploy Frontend to GCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./KTB-FE-main  # zip 파일 내부에 위치한 프로젝트 폴더

      - name: Build the project
        run: npm run build
        working-directory: ./KTB-FE-main

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r ./KTB-FE-main/dist gs://${{ secrets.GCS_BUCKET_NAME }}

      - name: (Optional) Invalidate Cloud CDN Cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache ${GCS_BUCKET_NAME} --path "/*"
        continue-on-error: true
